project:
  type: website
  output-dir: .

website:
  title: "ExeMaria"
  navbar:
    left:
      - href: https://mathbullet.github.io/ExeMaria/index
        text: Home
      - href: https://mathbullet.github.io/ExeMaria/about
        text: About
  sidebar:
    contents:
      - section: "大規模言語モデル"
        contents:
          - section: "Coding"
            contents:
              - text: "aisuite"
                href: "llm-coding/aisuite-tutorial.html"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true