project:
  type: website
  output-dir: docs

website:
  title: "ExeMaria"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    contents:
      - section: "大規模言語モデル"
        contents:
          - section: "Coding"
            contents:
              - text: "aisuite"
                href: "llm-coding/aisuite-tutorial.html"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



