project:
  type: website
  output-dir: docs

website:
  title: "ExeMaria"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    search: true
    contents:
      href: llm-coding/aisuite-tutorial.qmd
      text: aisuiteチュートリアル

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



